name: nightly-netlify-build

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[netlify ci]')"
    steps:
      - name: trigger netlify build
        run: |
          curl -X POST -d '{}' ${{secrets.NETLIFY_HOOK}}
